//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUIT2013.DataMining.Chi2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MUIT2013.DataMining.Chi2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF,0.995,0.975,0.2,0.1,0.05,0.025,0.02,0.01,0.005,0.002,0.001
        ///1,0.0000393,0.000982,1.642,2.706,3.841,5.024,5.412,6.635,7.879,9.55,10.828
        ///2,0.01,0.0506,3.219,4.605,5.991,7.378,7.824,9.21,10.597,12.429,13.816
        ///3,0.0717,0.216,4.642,6.251,7.815,9.348,9.837,11.345,12.838,14.796,16.266
        ///4,0.207,0.484,5.989,7.779,9.488,11.143,11.668,13.277,14.86,16.924,18.467
        ///5,0.412,0.831,7.289,9.236,11.07,12.833,13.388,15.086,16.75,18.907,20.515
        ///6,0.676,1.237,8.558,10.645,12.592,14.449,15.033,16.812,18.548,20.791,22.458
        ///7,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChiSquareDistributionTable {
            get {
                return ResourceManager.GetString("ChiSquareDistributionTable", resourceCulture);
            }
        }
    }
}
